export const defaultWordS = [
  { "text": "bodybuilding", "value": 12.5 },
  { "text": "fitness", "value": 10.5 },
  { "text": "powerlifting", "value": 9.0 },
  { "text": "muscles", "value": 7.5 },
  { "text": "nutrition", "value": 6.5 },
  { "text": "health", "value": 6.0 },
  { "text": "champion", "value": 5.0 },
  { "text": "athlete", "value": 4.5 },
  { "text": "workout", "value": 4.0 },
  { "text": "training", "value": 3.5 },
  { "text": "physique", "value": 3.5 },
  { "text": "motivation", "value": 3.0 },
  { "text": "strength", "value": 3.0 },
  { "text": "competition", "value": 2.5 },
  { "text": "flexibility", "value": 2.5 },
  { "text": "endurance", "value": 2.0 },
  { "text": "aesthetics", "value": 2.0 },
  { "text": "diet", "value": 2.0 },
  { "text": "supplements", "value": 2.0 },
  { "text": "lean", "value": 1.5 },
  { "text": "mass", "value": 1.5 },
  { "text": "stamina", "value": 1.5 },
  { "text": "body", "value": 1.5 },
  { "text": "physiology", "value": 1.0 },
  { "text": "anatomy", "value": 1.0 },
  { "text": "muscular", "value": 1.0 },
  { "text": "overcoming", "value": 1.0 },
  { "text": "dedication", "value": 1.0 },
  { "text": "mindset", "value": 1.0 },
  { "text": "inspiration", "value": 1.0 },
  { "text": "perfection", "value": 1.0 },
  { "text": "personal", "value": 0.5 },
  { "text": "development", "value": 0.5 },
  { "text": "life", "value": 0.5 },
  { "text": "career", "value": 0.5 },
  { "text": "motivational", "value": 0.5 },
  { "text": "speaker", "value": 0.5 },
  { "text": "author", "value": 0.5 },
  { "text": "modeling", "value": 0.5 },
  { "text": "acting", "value": 0.5 },
  { "text": "entertainment", "value": 0.5 },
  { "text": "television", "value": 0.5 },
  { "text": "film", "value": 0.5 }
  ]

  export const loadingWordS = [
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "it takes about 30 sec", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "it takes about 30 sec", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "Loading", "value": 1},
    { "text": "it takes about 30 sec", "value": 1},
    { "text": "Loading", "value": 1}
  ]
